### ISSUE TITLE
好像上下文会断了？

### ISSUE THREAD

**Issue by linkboy2007** [sunshanpeng/wechaty-chatgpt#1]
好像上下文会断了？

**Comment by sunshanpeng** [comment]
有具体一点的描述吗？

**Comment by linkboy2007** [comment]
我说一下情况。  如果有一个问题，回答比较长的话，在web页面，和chatgpt说继续，chatgpt就会继续回答。但是微信里面就显示 不知道继续什么东西。

**Comment by sunshanpeng** [comment]
已经支持上下文，不过上下文有个问题要注意下，之前的问题没有回复之前不能问下个问题
