### ISSUE TITLE
/chatgpt 建议改成@ 

### ISSUE THREAD

**Issue by linkboy2007** [sunshanpeng/wechaty-chatgpt#3]
群里的 /chatgpt 建议改成@  更加方便。

**Comment by linkboy2007** [comment]
@ 出现了bug。当机器人回复的时候 会自己 @  自己。导致重复回答问题。

**Comment by linkboy2007** [comment]
![image](https://user-images.githubusercontent.com/15963915/206630367-fa024c17-af24-4a88-b953-50877a9120a5.png)
重复回答问题

 回复的时候 会自己 @ 自己。导致重复回答问题

**Comment by sunshanpeng** [comment]
> ![image](https://user-images.githubusercontent.com/15963915/206630367-fa024c17-af24-4a88-b953-50877a9120a5.png) 重复回答问题
> 
> 回复的时候 会自己 @ 自己。导致重复回答问题

我试了一下，这种情况会发生在改过群聊昵称后，没改的时候是正常的，改了群聊昵称后确实会一直重复，我看看有没有办法兼容下

**Comment by linkboy2007** [comment]
谢谢 知道原因就方便了。改名就行了。
