### ISSUE TITLE
新版本会自动通过好友申请

### ISSUE THREAD

**Issue by linkboy2007** [sunshanpeng/wechaty-chatgpt#5]
新版本会自动通过好友申请，之前好像不会，这个可以用开关关闭吗？

**Comment by sunshanpeng** [comment]
开关这个我思考下，你可以先把index.js里的friendship这块去掉哈

**Comment by sunshanpeng** [comment]
main分支已经去掉自动通过好友了

**Comment by linkboy2007** [comment]
哈哈 好暴力。其实放个变量 if friend=1  自动通过 然后 friend 开头和 token一起配置一下 就好了

不过还是谢谢更新了。

另外问一下 /c 这个如果直接去了。是不是可以不用提示符，直接私聊对话了?

**Comment by sunshanpeng** [comment]
> 哈哈 好暴力。其实放个变量 if friend=1 自动通过 然后 friend 开头和 token一起配置一下 就好了
> 
> 不过还是谢谢更新了。
> 
> 另外问一下 /c 这个如果直接去了。是不是可以不用提示符，直接私聊对话了?

那需要判断下是群聊还是私聊，因为我本身不是写js的，代码写的不太优雅，推荐隔壁大佬的项目，我也在学习并给他们提交代码
[wechat-chatgpt](https://github.com/fuergaosi233/wechat-chatgpt)
