### ISSUE TITLE
ChatGPT failed to refresh auth token. Error: 403 Forbidden

### ISSUE THREAD

**Issue by yzcyayaya** [sunshanpeng/wechaty-chatgpt#6]
ChatGPT failed to refresh auth token. Error: 403 Forbidden

docker run -e SESSION_TOKEN="$(echo $SESSION_TOKEN)" --rm -it registry.cn-hangzhou.aliyuncs.com/sunshanpeng/wechaty-chatgpt:0.0.8

completed : 
`export SESSION_TOKEN='my token'`

why?

**Comment by waahah** [comment]
OpenAI has added some additional Cloudflare protections that prevent access to token refreshes

**Comment by waahah** [comment]
> ChatGPT failed to refresh auth token. Error: 403 Forbidden
> 
> docker run -e SESSION_TOKEN="$(echo $SESSION_TOKEN)" --rm -it registry.cn-hangzhou.aliyuncs.com/sunshanpeng/wechaty-chatgpt:0.0.8
> 
> completed : `export SESSION_TOKEN='my token'`
> 
> why?

OpenAI has added some additional Cloudflare protections that prevent access to token refreshes
